---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: default
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch-external.default.svc.cluster.local:9200"
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        sniffing => false
        codec => "json"
      }
      stdout { codec => rubydebug }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:6.5.4
        name: logstash
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
        resources:
          limits:
            memory: 4Gi
            cpu: "500m"
          requests:
            memory: 2Gi
            cpu: "200m"
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Europe/Moscow
      - name: pipeline
        configMap:
          name: logstash
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels:
    app: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - name: logstash
    nodePort: 31113
    port: 5044
    targetPort: 5044
    protocol: TCP
