apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - name: http
    nodePort: 31114
    port: 80
    targetPort: 5601
    protocol: TCP
