apiVersion: v1
kind: Service
metadata:
  name: cerebro-external
  labels:
    app: cerebro
    type: http
spec:
  type: NodePort
  ports:
  - nodePort: 31117
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: cerebro
