---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: localhost:5000/cerebro
        ports:
        - name: cerebro
          containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-external
  labels:
    app: cerebro
    type: http
spec:
  type: NodePort
  ports:
  - nodePort: 31117
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: cerebro
