---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-dev
  labels:
    k8s-app: filebeat
  namespace: monitoring
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    output.logstash:
      codec.json:
        pretty: false
      hosts: ['${LOGSTASH_HOST}:${LOGSTASH_PORT}']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-blobstorage-inputs-dev
  labels:
    k8s-app: filebeat
  namespace: monitoring
data:
  azureblob-dev.yml: |-
    - type: log 
      paths:
        - "/blobstorage-dev/log/cluster-logs/*/driver/log4j-active.log"
      close_inactive: 2m
    
