---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "cluster0"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-the-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: elasticseach-volume
          mountPath: /data
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-0.cluster0.monitoring.svc.cluster.local,elasticsearch-1.cluster0.monitoring.svc.cluster.local,elasticsearch-2.cluster0.monitoring.svc.cluster.local"
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx2048m
        ports:
        - name: http
          containerPort: 9200
        - name: tcp
          containerPort: 9300
        resources:
          requests:
            cpu: 0.5
            memory: "1024m"
          limits:
            cpu: 2
            memory: "2048m"
        volumeMounts:
        - name: elasticseach-volume
          mountPath: /data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: elasticseach-volume
    spec:
      storageClassName: azurefile
      accessModes: [ ReadWriteMany ]
      resources:
        requests:
          storage: 35Gi
