apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: monitoring
data:
  elasticsearch.yml: |+
    cluster.name: "es"
    network.host: 0.0.0.0
    path.data: /data
    discovery.zen.minimum_master_nodes: 1

    ### X-Pack
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.ml.enabled: false
    xpack.watcher.enabled: false
