apiVersion: v1
kind: Service
metadata:
  name: cluster0
  namespace: monitoring
  labels:
    app: elasticsearch
    type: headless
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: serving
  - port: 9300
    name: node-to-node
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
  namespace: monitoring
  labels:
    app: elasticsearch
    type: http
spec:
  type: NodePort
  ports:
  - nodePort: 31112
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
