apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - name: logstash-azureblob-dev
    nodePort: 31110
    port: 5040
    targetPort: 5040
    protocol: TCP
  - name: logstash-azureblob-stg
    nodePort: 31111
    port: 5041
    targetPort: 5041
    protocol: TCP
  - name: logstash-azureblob-prod
    nodePort: 31121
    port: 5042
    targetPort: 5042
    protocol: TCP
  - name: logstash-beats-k8s
    nodePort: 31122
    port: 5043
    targetPort: 5043
  - name: logstash-beats-hdikafka
    nodePort: 31123
    port: 5044
    targetPort: 5044
