---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-k8s
  labels:
    k8s-app: filebeat
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    output.logstash:
      codec.json:
        pretty: false
      hosts: ['${LOGSTASH_HOST}:${LOGSTASH_PORT}']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs-k8s
  labels:
    k8s-app: filebeat
  namespace: kube-system
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
    
